properties([parameters([string(name: 'Bucket1_Name', defaultValue: 'abhi-jenkins'),string(name: 'Bucket2_Name', defaultValue: 'packer-intro')])])
pipeline {
    agent {
        docker {
            image 'devopscafe/maven-awscli'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
            post {
                success  {
                    emailext  (
                to: "abhishek.dudi.9@gmail.com",
                subject: "Job was Successful: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'",
                body: """=== Job Details as Below === 
                  Job Name = '${env.JOB_NAME}'
                  Job Build Number = '${env.BUILD_NUMBER}'
                  Build Info @ '${env.BUILD_URL}' 
                  """  
                )
            }
                failure  {
                    emailext  (
                to: "abhishek.dudi.9@gmail.com",
                subject: "Job Failed: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'",
                body: """=== Job Details as Below === 
                  Job Name = '${env.JOB_NAME}'
                  Job Build Number = '${env.BUILD_NUMBER}'
                  Build Info @ '${env.BUILD_URL}' 
                  """
            )
                }
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
        stage('Store-in-S3-Bucket-1') {
            steps {
                sh "aws s3 cp /var/lib/jenkins/workspace/jenkins-intro/target/my-app-1.0-SNAPSHOT.jar s3://${params.Bucket_Name}/"
            }
        }
        stage('Stage-in-S3-Bucket-2') {
            steps {
                sh "aws s3 cp /var/lib/jenkins/workspace/jenkins-intro/target/my-app-1.0-SNAPSHOT.jar s3://${params.Bucket2_Name}/"
            }
        }
    }
}
